### ISSUE TITLE
Intermittent test failures: init-deployment and init-statefulset

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/open-liberty-operator#464] opened 2023-08-28 14:37 UTC
[OLO CI Build #240](https://cloud.ibm.com/devops/pipelines/tekton/b641bb1b-192f-4530-a810-b92ce07c2b64/runs/feefc05f-489a-43ab-a4f8-bc47e8d5413b/deploy-acceptance-tests/run-stage?env_id=ibm:yp:us-south)

```
	Name: init-deployment
	State: fail

	Errors:
		resource Pod:olo-test-240/: .status.initContainerStatuses.name: value mismatch, expected: init1 != actual: scorecard-untar
		
	Name: init-stateful
	State: fail

	Errors:
		resource Pod:olo-test-240/: .spec.initContainers.name: value mismatch, expected: init1 != actual: scorecard-untar
```

Similar error in [RCO CI Build #526](https://cloud.ibm.com/devops/pipelines/tekton/729b3aea-0a81-4b4d-bd42-7e5811980010/runs/a7e72b27-e518-4849-89b4-b24e7bef0f6d/deploy-acceptance-tests/run-stage?env_id=ibm:yp:us-south)

**Comment by kabicin** [comment] 2023-09-25 20:08
@leochr I reproduced the error using a pause container as the initContainer image which causes the initContainer not to create properly. The image seems to be the reason for failure and because it is intermittent, the current registry is likely unreliable. We can switch to Red Hat registry using `registry.access.redhat.com/ubi9-micro` as an alternative (~2MB larger) and track to see if it reoccurs again.

**Comment by yongja79** [comment] 2023-10-23 14:04
[PR52](https://github.ibm.com/websphere/operators/pull/52) Fixes the issue on x, P and Z but still fails on Kind see [wlo build 1617](https://cloud.ibm.com/devops/pipelines/tekton/c3b2797d-c8ad-4dab-9660-2ec8c0643a76/runs/0b77f911-c250-475a-8b9e-79a0ae9fd984/deploy-acceptance-tests/run-stage?env_id=ibm:yp:us-south)

**Comment by kabicin** [comment] 2023-10-23 23:14
@yongja79 The fix should be merged now through Melissa's changes https://github.ibm.com/websphere/operators/pull/66.

**Closed** 2023-11-07 15:38 UTC
Labels: zenhub-dev, test-failure
