### ISSUE TITLE
There appears to be a timig issue in the Open Liberty Operator that prevents the pod from starting if the tls secret is not available when pulling the image from the internal OSCP registry

### ISSUE THREAD

**Issue by kpostreich** [OpenLiberty/open-liberty-operator#236] opened 2021-07-19 20:19 UTC
### What did you do?
using a Tekton pipeline to deploy a Java Liberty app to OSCP, the pod often fails to start because the tls secret that gets created is  not always available by the time the pod tries to pull the image from the OSCP image registry. 

In an automated devops process, I can do a delete pod or redo the deploy step, and it works. But by then, the tls secret ALWASY is present. 

A clear and concise description of the steps you took (or insert a code snippet).

Here is the public github repo that has the Tekton tasks and pipeline used, along with the dockerfile, etc that we are using. 
Deploying to OSCP 4.6.
https://github.com/kpostreich/devops-management

### What did you expect to see?

The oc-deploy-klp.yaml should deploy the app which uses the Open Liberty Operator.  All works, excpet pod fails to start for the reason mentioned in this bug  report. 
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-cm
spec:
  inputs:
    resources:
      - name: runtime-modernization-git
        type: git
  params:
      - name: pathToContext
        type: string
        default: /workspace/runtime-modernization-git
      - name: targetNamespace
        type: string
        default: dev
  steps:
    - name: deploy-open-liberty
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      script: |
        #!/bin/bash
        oc kustomize /workspace/runtime-modernization-git/deploy/overlay-apps
        oc apply -k /workspace/runtime-modernization-git/deploy/overlay-apps -n dev
        echo "Done deploying open liberty application"
        sleep 15
        ROUTE=$(oc get route cos --template='{{ .spec.host }}')
        echo "http://${ROUTE}/CustomerOrderServicesWeb"

### What did you see instead?

RRORS in the pod. 
   MountVolume.SetUp failed for volume "svc-certificate" : Secret "cos-tls" not found. 

  Failed to pull image...... Unauthorized: authentication required. 

A clear and concise description of what you expected to happen (or insert a code snippet).

Tekton deploy task using Open Linerty Operator to successfully deploy the application to OSCP v 4.6 

### Environment
I have a Skytap lab environment that can be used. The template is: https://cloud.skytap.com/templates/2056963?project_id=114366

### Possible solution

It is uclear to the end user when the tls secret gets created by the Open Liberty Operator. From what I can see, it appears to be created when the "service" is created, which is AFTER the deployment. My recommendation is to create the tls secret BEFORE the pod requires access to it in order to pull the image from the OSCP repo. 

### Additional context

We are writing up a hands-on lab guide that leverages the Tekton tasks and environment specified in this bug report. 

You may want to request access to this material for the steps we are using, if the content in this TEXT ONLY issue repoert is not sufficient to determine root cause.

**Comment by halim-lee** [comment] 2021-10-06 17:42
Hi @kpostreich, I tried deploying the Java Liberty app using the provided file in your repo (under `tekton-pipeline`). I tested them both on Fyre OCP cluster and Skytap test environment - but I was not able to reproduce the error.
Is this deployment order correct? This is from deploy.sh:
  1. oc create -f img-resource.yaml
  2. oc create -f git-resource.yaml
  3. oc create -f buildah.yaml
  4. oc create -f oc-deploy-klp.yaml
  5. oc create -f pipeline-deploy.yaml
  6. oc create -f pipeline-deploy-run.yaml

**Comment by kpostreich** [comment] 2021-10-06 19:12
Please look at the content in the deploy yaml files.

In order to work around the issue, we inserted a command to restart the
Liberty pod. If you remove that, you will see the issue (but know it seems
like  timig issue) so it may take a few attempts to recreate the issue.

Verify in the Liberty Operator that the secrets / configmaps are created
and ready before the pod tries to start. It seems like the Liberty pod
tries to start before the secret/configmaps are created on the cluster.

Thanks;

Kevin Postreich
WW IBM Automation, Integration Technical Sales Leader IBM Technology Sales
Certified Master Consulting I/T Specialist
Certified IBM WebSphere Application Server Specialist
Mobile: (919) 604-4487
***@***.***










From:	"Melissa Lee" ***@***.***>
To:	"OpenLiberty/open-liberty-operator"
            ***@***.***>
Cc:	"kpostreich" ***@***.***>, "Mention"
            ***@***.***>
Date:	10/06/2021 01:42 PM
Subject:	[EXTERNAL] Re: [OpenLiberty/open-liberty-operator] There
            appears to be a timig issue in the Open Liberty Operator that
            prevents the pod from starting if the tls secret is not
            available when pulling the image from the internal OSCP
            registry (#236)



Hi @kpostreich, I tried deploying the Java Liberty app using the provided
file in your repo (under tekton-pipeline). I tested them both on Fyre OCP
cluster and Skytap test environment - but I was not able to reproduce the
error. Is this deployment 


Hi @kpostreich, I tried deploying the Java Liberty app using the provided
file in your repo (under tekton-pipeline). I tested them both on Fyre OCP
cluster and Skytap test environment - but I was not able to reproduce the
error.
Is this deployment order correct? This is from deploy.sh:
      oc create -f img-resource.yaml
      oc create -f git-resource.yaml
      oc create -f buildah.yaml
      oc create -f oc-deploy-klp.yaml
      oc create -f pipeline-deploy.yaml
      oc create -f pipeline-deploy-run.yaml


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by leochr** [comment] 2022-03-28 12:44
Open Liberty Operator v0.8.1 is now released with the fix for this issue. Release information is documented [here](https://github.com/OpenLiberty/open-liberty-operator/releases/tag/v0.8.1).

fyi @kpostreich

**Closed by leochr** 2022-03-28 12:44 UTC
